# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- development

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0
- task: SonarCloudPrepare@2
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'be-studio'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'be-studio_Sensum'
    cliProjectName: 'Sensum'
    cliSources: '.'
- task: SonarCloudAnalyze@2
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'