# BASE
FROM node:latest AS base
LABEL maintainer="Be Studio <hello@its-be-studio.com>"
LABEL version="1.0"
WORKDIR /app

# DEPENDENCIES
FROM base AS dependencies
COPY ./package.json .
RUN npm install
EXPOSE 3000

# BUILDS
# Development
FROM dependencies AS build
COPY . /app
#RUN useradd -u 1234 non-root
#USER non-root

# Production
FROM nginx:1.17.9-alpine AS release
#USER root
COPY /docker/nginx.conf /etc/nginx/nginx.conf
WORKDIR /app
COPY ./dist ./
#USER non-root
