from .base import Base
from .user import *
from .user_group import *
from .user_permission import *
from .course import *
from .lecturer import *
from .event import *
from .seat import *
from .offer import *
from .sponsor import *
from .course_additional_info import *
