from .base import Base
from .user import User
from .user_group import UserGroup
from .user_permission import UserPermission
from .course import Course
from .lecturer import Lecturer
from .event import Event
from .seat import Seat
from .offer import Offer
from .sponsor import Sponsor
from .course_additional_info import CourseAdditionalInfo
