# Generated by Django 5.0.4 on 2024-08-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensum', '0002_updated_user_added_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_app_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Last Logged into App'),
        ),
    ]
